services:
    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 30s
    server:
      container_name: prakticum-server
      image: prakticum-server
      build:
        context: .
        dockerfile: Dockerfile.server
        args:
          SERVER_PORT: ${SERVER_PORT}
      restart: always
      ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
      environment:
        SERVER_PORT: ${SERVER_PORT}
        DB_HOST: postgres
        DB_PORT: ${POSTGRES_PORT}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Передаём данные для подключения
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        postgres:
          condition: service_healthy
    client:
      container_name: prakticum-client
      image: prakticum-client
      build:
        context: .
        dockerfile: Dockerfile.client
        args:
          CLIENT_PORT: ${CLIENT_PORT}
      restart: always
      ports:
        - "${CLIENT_PORT}:80"
      environment:
        - CLIENT_PORT=${CLIENT_PORT}
        - SERVER_PORT=${SERVER_PORT}
        - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
        - INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}
      depends_on:
        postgres:
          condition: service_healthy
        server:
          condition: service_started